channels:
  - conda-forge
dependencies:
  - descartes==1.1.0
  - pyproj==2.5.0
  - matplotlib==3.1.3
  - numpy==1.18.1
  - osmnx==0.11.4
  - shapely==1.7.1
  - owslib==0.19.1
  - appmode==0.7.0
  - mercantile==1.1.5
  - rasterio==1.1.8
  - affine==2.3.0

