channels:
  - conda-forge
dependencies:
  - descartes==1.1.0
  - pyproj==2.6.1.post1
  - matplotlib==3.3.2
  - numpy==1.19.2
  - osmnx==0.16.1
  - shapely==1.7.1
  - owslib==0.19.1
  - appmode==0.8.0
  - mercantile==1.1.6
  - rasterio==1.1.8
  - affine==2.3.0

